### ISSUE TITLE
keyboard actions doesn't work

### ISSUE THREAD

**Issue by Efimj** [MohamedRejeb/Compose-Rich-Editor#155]
Hi
I noticed that
```
keyboardActions = KeyboardActions(
                 onAny = {
                     Log.i("d","sdsax")
                     state.setText("\n\n")
                 }
             )
```
doesn't work in **BasicRichTextEditor**, please check this logic

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for reporting this issue. I will check it out.

**Comment by MohamedRejeb** [comment]
It's working the same the Compose `TextField`, you need to specify an `ImeType` in your `KeyboardOptions` in order to be able to listen for `KeyboardActions`. If you try it with Compose `TextField` you will have the same behaviour.
Also, if you specify a custom `ImeType` you will not be able to add line breaks with the keyboard.

**Comment by MohamedRejeb** [comment]
I closed the issue because `KeyboardActions` is working as expected but feel free to explain your needs.
