### ISSUE TITLE
Question: Why do you replace the line breaks with a space?

### ISSUE THREAD

**Issue by jjrodcast** [MohamedRejeb/Compose-Rich-Editor#158]
I saw in the code that you are replacing the line breaks with spaces, but what is the reason, can you explain with an example?

**Comment by MohamedRejeb** [comment]
Hi, it's a workaround because the compose text field has a lot of issues with rich text.
Replacing line breaks with spaces is fixing two issues (One fixed by removing line breaks and one fixed by adding spaces).
1. If I'm going to work with ParagraphStyle and I added two paragraphs for example, compose will add line break by default between paragraphs, so if I have line break on the string as well, we will have two line breaks, but we should only have one. That's why I'm removing the line breaks. `Demo text \n second paragraph` => `<ParagraphStyle>Demo text</ParagraphStyle> <ParagraphStyle>second paragraph</ParagraphStyle>`
2. For adding spaces after the end of each paragraph. It's a workaround to fix a bug in Compose selection when we have multiple paragraphs. If I don't add spaces the last letter of each paragraph is not going to be selectable.

I hope it's clear.

**Comment by MohamedRejeb** [comment]
I hope that with the new `BasicTextField2` things will become easier.
I will close this issue, feel free to reopen it if you still have more questions.
