### ISSUE TITLE
Some RichTextStyle(s) are not recognized on creating RichTextValue from HTML String

### ISSUE THREAD

**Issue by MohamedRejeb** [MohamedRejeb/Compose-Rich-Editor#32]
The RichTextStyle(s) that are not recognized are the styles created using the `object : RichTextStyle`.
The comparison between RichTextStyle(s) should be improved to be something like comparing SpanStyle(s) and making a SpanStyle value as a member for the RichTextStyle interface.
Also there's some intentions to totally remove the RichTextStyle and simply use the SpanStyle to simplify handling these cases.

**Comment by Faisals3** [comment]
Hello. 
I am trying to save the content of the text into a database witch is done correct by using the `.toHtml()` function

but when importing from database `richTextValue = RichTextValue.from(item.text)`
the output of the `richTextValue` is not correct for the `<br>` tags. It gets removed and replaced with <p></p> tags.
When saving to database the input is : `<p>2<br><br><br><br><br></p><p>2</p>`
but when importing from database the output is : `<p>2</p><p>2</p>`

any idea how to fix this ? or am I trying to save it and upload it in the wrong way ?

Thanks.

**Comment by MohamedRejeb** [comment]
Hi Faisal,
Can provide a simple code of your use case

**Comment by Faisals3** [comment]
This is the function responsible for adding and updating the database : 
`fun handleCreateAndUpdateNote(
    noteRepository: NoteRepository,
    action: String,
    titleText: TextFieldValue,
    textState: RichTextValue,
    createdNoteForFirstTimeFlag: Boolean,
    setCreatedNoteForFirstTimeFlag: (Boolean) -> Unit,
    folderId: Int,
    noteId: Int,
    indexOfLastNoteCreated: Int,
) {
    //create note in db
    if (action == "create" && !createdNoteForFirstTimeFlag && (titleText.text.isNotEmpty() || textState.toHtml().isNotEmpty())) {
        noteRepository.addNote(
            Note(
                title = titleText.text,
                content = textState.toHtml(),
                folderId = folderId,
                createdAt = Date(),
                updatedAt = Date(),
            )
        )
        setCreatedNoteForFirstTimeFlag(true)
    }
    //update created note from this screen
    else if (action == "create" && createdNoteForFirstTimeFlag) {
        noteRepository.updateNote(
            noteId = indexOfLastNoteCreated,
            title = titleText.text,
            content = textState.toHtml(),
            updatedAt = Date(),
        )
    }
    //update note by passed id
    else if (action == "update") {
        noteRepository.updateNote(
            noteId = noteId,
            title = titleText.text,
            content = textState.toHtml(),
            updatedAt = Date(),
        )
    }
}`

and this is the part of the function is to import the content from the database later :
`
titleText = TextFieldValue(text = noteDetail.title)
richTextValue = RichTextValue.from(noteDetail.content)
`

**Comment by Faisals3** [comment]
My richTextField variable : `var richTextValue by remember { mutableStateOf(RichTextValue()) }`
writing to database : `noteRepository.addNote( Note(content = richTextValue.toHtml()))
reading from database : `richTextValue = RichTextValue.from(noteDetail.content)`

**Comment by MohamedRejeb** [comment]
That's weird, I will give it a try and see. I'm working on fixing all the problems related to converting HTML back to `RichTextValue`. But there's something that is not clear yet, how to new value is `<p>2</p><p>2</p>` and it's `RichTextValue`, it shouldn't contain HTML elements

**Comment by Faisals3** [comment]
The issue is even the text coming from HTML text is a miss and has new line breaks that either wasn't there in the original text. or it will remove it completely.
Will attach some pictures for what is happening to me when using the encoding and decoding html functions : 
1 - writing text for first time and save it to string by `.toHtml()` 
![1](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/41377014/ec363c3b-b492-4249-9a60-d78329203405)

2 - reading text saved by `.toHtml()` before and update `richTextValue = RichTextValue.from(savedString)` , output :
![2](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/41377014/a4637f2d-8fa5-427d-9cd2-fba694bd2a8e)

3 - after writing and reading without changing the text, "just used `.toHtml()` and `.form(string)`  again" , this is the output of the text :
![3](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/41377014/f78d38c8-1d8c-4747-984f-2285d2d2683a)

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I'm working on it, it should be fixed today inchallah
