### ISSUE TITLE
Support `RichTextState.toText`

### ISSUE THREAD

**Issue by Goooler** [MohamedRejeb/compose-rich-editor#321]
Call `basicRichTextState.annotatedString.toString()` to obtain plaintext,
- expect: `this\nis`
- actual: `this is`

I'm using `com.mohamedrejeb.richeditor:richeditor-compose:1.0.0-rc05-k2`, you can repro this in #320.

**Comment by Goooler** [comment]
There is no plaintext parser or `RichTextState.toPlainText` API, can we may consider providing a new access for this.

**Comment by MohamedRejeb** [comment]
That's the expected result from `annotatedString`, that's due to Compose Text API limitations, they don't provide proper support for using different paragraphs into the annotated string.
Yes, we need a new `toText` method, I think it's better to call it `toText` to match with the already existing one `setText`.
This method will loop through all paragraphs, merge plain text string and append a new line at the end of each paragraph..

**Comment by Goooler** [comment]
Thanks! That would be very handy. As a workaround, I'm converting plaintext from the output markdown.
