### ISSUE TITLE
Richtext cursor fixed at position 0

### ISSUE THREAD

**Issue by spach10** [MohamedRejeb/Compose-Rich-Editor#52]
I am trying to instantiate the remember delegate with a starting value when in the editing state. It always shows as an empty description state :/ Here's the code and a screenshot below:

```
var richTextValue by remember { mutableStateOf(RichTextValue.from(htmlStringFromBackend)) }

RichTextEditor(
    enabled = enabled,
    modifier = innerModifier.fillMaxWidth(),
    value = richTextValue,
    onValueChange = {
        richTextValue = it
    },
    colors = TextFieldDefaults.textFieldColors(backgroundColor = Color.White),
)
```
![Screenshot 2023-06-12 at 1 08 39 PM](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/19916794/7652a68d-2e49-4eaf-b510-0588a8553c86)

How can I fix this so it will start with loading in the data?

**Comment by MohamedRejeb** [comment]
Hi, can you share with me a sample html code that you've entered.
Also, this could be a problem with using Compose because if `htmlStringFromBackend` is a state and it's initial value is an empty string then if it gets updated nothing is going to happen, try this instead.

`var richTextValue by remember(htmlStringFromBackend) { mutableStateOf(RichTextValue.from(htmlStringFromBackend)) }`

Also for now initializing the RichEditor with an HTML string still have few problems and I'm working on a fix for that which is going to be released soon.

**Comment by MohamedRejeb** [comment]
You shouldn't use from(html) and toHtml() with each digit edited, just use toHtml when you submit your form because there's no way to save the cursor position in a html string. Also you could separate the `htmlStringFromBackend` that you are going to use in `from()` from the state where you are going to save the final html string with `toHtml()`, to make sure that the `htmlStringFromBackend` is going to be used only for initializing the rich text for the first time.

**Comment by MohamedRejeb** [comment]
Check out the latest version
