### ISSUE TITLE
Support Initializing / setting the RichTextState from TextFieldValue / Annotated String

### ISSUE THREAD

**Issue by wakaztahir** [MohamedRejeb/Compose-Rich-Editor#66]
Right now rememberRichTextState has no parameters , I would like to initialize rememberRichTextState via text field value / annotated string

There's also no function setTextFieldValue , setAnnotatedString , but there's setText

This would make it easier to replace OutlinedTextField with OutlinedTextEditor , since we only need to initialize / set the text field value to rich text state and provide rich text state to editor

**Comment by MohamedRejeb** [comment]
I'm thinking of something like that, for initializing rememberRichTextState with `TextFieldValue` it should be easy, but for the annotated string it's quite complex and require some work. Also the setTextFieldValue is quite similar to setText, the only thing that makes the difference is the selection.

**Comment by MohamedRejeb** [comment]
Btw I prefer using that setText or setHtml methods because it gives more flexibility and it's not related to compose, also you can call setHtml more than a single time on the same `RichTextState`, but for `rememberRichTextState` when you pass something to it like text for example and that text passed is a state and it changes, the changes are not going to be applied.

**Comment by wakaztahir** [comment]
@MohamedRejeb Can the user be given access to underlying text field value ?

**Comment by MohamedRejeb** [comment]
He has access to the selection and the annotated string and that's what text field value provides, so there's no need for making text field value public.
