### ISSUE TITLE
How to clear all formatting

### ISSUE THREAD

**Issue by sayler666** [MohamedRejeb/Compose-Rich-Editor#75]
Is there a simple way to clear all the formatting?

**Comment by MohamedRejeb** [comment]
For removing span styles, such as (bold, italic...), you can use:
`removeSpanStyle(SpanStyle())`

For removing paragraph styles, you can use:
`removeParagraphStyle(ParagraphStyle())`

Also you will need to call `removeCode()` as well
Idk if you will need to remove ordered/unordered lists because it's going to update the current paragraph, it doesn't make much sense.

This is the simplest way for know, I'll try to improve it more.

**Comment by sayler666** [comment]
Not sure if I understand correctly but when I use 
`state.removeSpanStyle(SpanStyle())`
Nothing happens.
It seems like I need to pass concrete SpanStyle like 
`state.removeSpanStyle(SpanStyle(fontWeight = FontWeight.Bold))` to make it work, but this way I would need to pass every type of span style just to clear formatting.

**Comment by MohamedRejeb** [comment]
Ah that's correct, you can try this and it's going to remove the current applied span styles:
removeSpanStyle(richTextState.currentSpanStyle)

**Comment by sayler666** [comment]
Thanks, that worked!

**Comment by Goooler** [comment]
Can we add a new API like `removeAllSpanStyle()` to finish this? It would be handy and clear for users.

**Comment by MohamedRejeb** [comment]
Yes, I think that's easier than passing the currentSpanStyle.

**Comment by Goooler** [comment]
This has been fixed in #324, now you can call `clearSpanStyles` and `clearRichSpans`.
