### ISSUE TITLE
Question: Can you explain how parent and children are update? 

### ISSUE THREAD

**Issue by jjrodcast** [MohamedRejeb/Compose-Rich-Editor#91]
I have some doubts understanding how parent and childrens are updated. Can you provide some examples here about how they are stored ?

Thanks in advance.

**Comment by MohamedRejeb** [comment]
The rich text is stored in a tree where the first children are paragraphs and the rest are spans, here's a simple example, I'm thinking of providing a detailing explanation on how it works. There's a lot of things happening when you type something in the middle of when you add a new line, I need to move the nodes after selection to the next paragraph, there's a lot of other cases to handle as well. The good think about this approach is that I can easily convert it to HTML and convert HTML to rich text tree since HTML uses the same logic and represented as a tree.

![Screenshot 2023-08-10 at 6 47 51 AM](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/41842296/9f16a081-d5fb-4673-bb66-3e25c4e1cb53)
